name: Daily YouTube Podcast Summary

on:
  schedule:
    # 每天北京时间早上8点运行 (UTC 00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run podcast summarizer
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        OPENROUTER_MODEL: ${{ secrets.OPENROUTER_MODEL }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
        EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
      run: |
        python src/main.py --once

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: logs/

    - name: Upload reports
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: reports
        path: reports/